"""
Django settings for xy_neo4j project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

from .get_ali_response import GetAliResponse
from .get_kimi_response import GetKimiResponse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-j^gdmnj#)*-%e$df9gsf&$(*l+*t=e3mi#&m-^)_xf-@msk1yc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'myneo4j',
    'accounts'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'xy_neo4j.urls'
#模板建立
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'xy_neo4j.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases
LLM_PROVIDERS = {#配置路由，
    'kimi': 'KIMI',    # 对应 settings.KIMI.get_response()
    'ali': 'ALI',      # 对应 settings.ALI.get_response()
    'zhipu': 'ZHIPU',  # 对应 settings.ZHIPU.get_response()
    'deepseek': 'DEEPSEEK'  # 对应 settings.DEEPSEEK.get_response()
}
# 默认模型 (建议选择最稳定的)修改中.......
DEFAULT_LLM = 'kimi'

#数据库，这里选择SQLite
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',#当前base目录/db.sqlite文件
    }
}



AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/
#静态css和image资源项
STATIC_URL = '/static/'


STATIC_DIRS = (
    os.path.join(BASE_DIR, 'static')
)
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

X_FRAME_OPTIONS = 'SAMEORIGIN'

DATAS_DIR = os.path.join(BASE_DIR, "datas")

#API集成
X_FRAME_OPTIONS = 'SAMEORIGIN'
ZHIPUAI_API_KEY = '9c62676e51d84d09955cc6ade617491d.4LKMlx2Zvk6849TV'
DEEPSEEK_API_KEY = 'sk-97a2aab4b1d64834b4805c90b21933ef'
DOUBAO_API_KEY='4cb99985-8f4d-4a3e-a300-c89620fab2ae'
ANYUE_API_KEY='sk-Fj9mAA1l3SKLWAJZJLAQvCn0gFX7HlANQInZPCKH8PSQkndl'
ALIBABA_API_KEY='sk-5bb14446a85842769d8cf237e08e8099'

# 新增：媒体文件配置，这里预设保存生成的内容
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'media')

SIMPLEUI_HOME_INFO = False
SIMPLEUI_ANALYSIS = False

AUTH_USER_MODEL = 'accounts.UserProfile'
LOGIN_URL = '/accounts/login'
LOGIN_REDIRECT_URL = '/'
LOGOUT_URL = '/accounts/logout'

#全员引用
from .question_classifier import *
from .question_parser import *
from .answer_search import *
from .get_zhipu_response import *
from .get_deepseek_response import *
CLASSIFIER = QuestionClassifier()
PARSER = QuestionPaser()
SEACHER = AnswerSearcher()
ZHIPU = GetZhipuResponse()
DEEPSEEK = GetDeepSeekResponse()
ALI=GetAliResponse()
KIMI=GetKimiResponse()